### PR TITLE
Windows support

### LINKED ISSUE #26: Windows support (project migrated from Xamarin using Redth/ZXing.Net.Mobile)
Hi Redth,
     ZXing.Net.Mobile is awesome! 
     My project was migrated from Xamarin to MAUI recently. But when testing it on Windows, 
the page which contains the ZXing.Net.Maui barcode reader shows "Not Supported". Could you please support WinUI so it covers desktop scenarios?

### PR DESCRIPTION
**Pull request by paoldev**
Fixes  #26 

I added Windows support for an application of mine.
It's mainly based on documentation found at https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/process-media-frames-with-mediaframereader, as a replacement for the CaptureElement.

I tested it with an USB camera, although the camera doesn't support focus and torch features, so that related part is still untested.

This PR may require additional code clean-up and refactoring as suggested by any possible review.
For example, it supports autodetection of camera connection and disconnection: the original CaptureElement seems to not support this feature, so it may be removed from this PR to keep the code aligned to CaptureElement behaviour (and autodetection code may be moved at application level).
The relevant file is CameraManager.windows.cs.

Let me know if this PR may be useful as a Windows starting point; feel free to close it if not needed.
Regards

### CODE REVIEW

**Comment by SunshineSpring666** [comment]
Hi guys,
The Windows support is quite great. It makes the cross-platform lib support all major platforms, making code scanning available for most desktop devices. 
Could the author @Redth please merge this feature into the main branch and release a NuGet package? 
Thanks a lot.
Best Regards

**Review by Redth — APPROVED** [review]

**Comment by daveblt** [comment]
Hello, I'd like to ask is the merging of this pull request means that the barcode reader will be supported on Windows now? Or does it need something more to fully function?

**Comment by paoldev** [comment]
@daveblt This PR added initial support for Windows scanner, but PR #146 may be required to make it more stable (when closing camera stream), mainly for AppShell applications.

**Comment by daveblt** [comment]
Understood, thank you! Much appreciated.

**Pull request merged**
