### PR TITLE
Camera resources relese

### PR DESCRIPTION
**Pull request by janmarektelc**
Camera resources are released, NFC reader is available after barcode reader usage.

#118

### CODE REVIEW

**Comment by juezen** [comment]
I had an issue where this plugin didn't release "camera2" for Android properly. This PR solved my problem! Need to be merged!

**Comment by joaquincubero22** [comment]
Hello, we need this merge for an Implementation that is failing without this PR, when opening a session of the ZXing and then close it and open the camera2 it fails with this fix it works.

**Comment by Yurinabaia** [comment]
Could you analyze this PR to include in the library

**Comment by EGoverde** [comment]
This PR fixed an issue for me when I try to use the camera preview from another package it won't work if the barcode view was shown earlier. This properly cleans the resources up so it can be used again elsewhere. Would like it to be merged as well!

**Comment by Silverdark** [comment]
This PR solves the issue for me as well. 
@Redth please check if you could merge it, I would appreciate it.

**Comment by aluna-magaya** [comment]
This PR fixes an issue I'm facing. I would appreciate if it gets merged. @Redth

**Comment by Silverdark** [comment]
Hi @Redth, I would be grateful if you could check this PR 🙂

**Comment by figuerres** [comment]
is there a way to get a version with this fix to test with ?  i am not a wizzard at how all this github pull stuff...... but i need a working version to not make users have to re-start an app for each barcode they read.

**Comment by EGoverde** [comment]
> is there a way to get a version with this fix to test with ? i am not a wizzard at how all this github pull stuff...... but i need a working version to not make users have to re-start an app for each barcode they read.

Until merged the fix is only available in the repository by @janmarektelc . If you want to use it until it is finally merged and the NuGet is updated, you can include the source in your own project. In that case head to the below URL and download the source either as a ZIP file or by cloning it.

https://github.com/janmarektelc/ZXing.Net.Maui/tree/bugfix-118-release-camera-resources

Once you have the source locally add it to your app by adding a project reference to the .csproj. Don't forget to remove the NuGet as well.

@Redth without this PR the project cannot really be used in a production environment. Please, please merge and update the package.

**Pull request merged**
